Flyers\PlanITBundle\Entity\Charge:
  type: entity
  table: charge
  repositoryClass: Flyers\PlanITBundle\Repository\ChargeRepository
  fields:
    idcharge:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    description:
      type: text
      nullable: true
    date:
      type: datetime
      nullable: false
#    end:
#      type: datetime
#      nullable: false
    duration:
      type: float
      nullable: false
  manyToOne:
    assignment:
      targetEntity: Assignment
      cascade: [ "detach" ]
      mappedBy: null
      inversedBy: null
      joinColumns:
        project:
          onDelete: CASCADE
          referencedColumnName: idassignment
      orphanRemoval: false
  manyToMany:
    persons:
      targetEntity: Person
      cascade: [ "detach" ]
      joinTable:
        name: charge_persons
        joinColumns:
          idassignment:
            onDelete: CASCADE
            referencedColumnName: idcharge
        inverseJoinColumns:
          idperson:
            onDelete: CASCADE
            referencedColumnName: idperson
