Flyers\PlanITBundle\Entity\Person:
  type: entity
  table: person
  repositoryClass: Flyers\PlanITBundle\Repository\PersonRepository
  fields:
    idperson:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    lastname:
      type: string
      length: 45
      fixed: false
      nullable: false
    firstname:
      type: string
      length: 45
      fixed: false
      nullable: false
    mail:
      type: string
      length: 45
      fixed: false
      nullable: false
    phone:
      type: string
      length: 45
      fixed: false
      nullable: true
    salary:
      type: decimal
      scale: 2
      nullable: true
  manyToOne:
    job:
      targetEntity: Job
      cascade: [ "persist" ]
      mappedBy: null
      inversedBy: null
      joinColumns:
        job:
          referencedColumnName: idjob
      orphanRemoval: false
  manyToMany:
    projects:
      cascade: [ "persist" ]
      targetEntity: Project
      joinTable:
        name: project_persons
        joinColumns:
          idperson:
            referencedColumnName: idperson
        inverseJoinColumns:
          idproject:
            referencedColumnName: idproject
