Flyers\PlanITBundle\Entity\Role:
  type: entity
  table: role
  repositoryClass: Flyers\PlanITBundle\Repository\RoleRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 255
      fixed: false
      nullable: false
