Flyers\PlanITBundle\Entity\User:
  type: entity
  table: user
  repositoryClass: Flyers\PlanITBundle\Repository\UserRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    username:
      type: string
      length: 255
      fixed: false
      nullable: false
    password:
      type: string
      length: 255
      fixed: false
      nullable: false
    salt:
      type: string
      length: 255
      fixed: false
      nullable: false
  manyToMany:
    userRoles:
      targetEntity: Role
      cascade: [ "persist" ]
      joinTable:
        name: user_roles
        joinColumns:
          iduser:
            referencedColumnName: id
        inverseJoinColumns:
          idrole:
            referencedColumnName: id
