# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

PlanitBundle:
    resource: "@PlanITBundle/Resources/config/routing.yml"
    prefix: /