PlanITBundle_index:
    pattern:  /
    defaults: { _controller: PlanITBundle:User:login }

PlanITBundle_homepage:
    pattern:  /planIT
    defaults: { _controller: PlanITBundle:Default:planit }
    
PlanITBundle_contact:
    pattern:  /contact
    defaults: {_controller: PlanITBundle:Default:contact }
    
PlanITBundle_about:
    pattern:  /about
    defaults: {_controller: PlanITBundle:Default:about }

PlanITBundle_login_check:
    pattern:  /planIT/login_check
    
PlanITBundle_login:
    pattern:  /login
    defaults: {_controller: PlanITBundle:User:login }
    
PlanITBundle_logout:
    pattern:  /logout
    defaults: {_controller: PlanITBundle:User:logout }
    
PlanITBundle_register:
    pattern:  /register
    defaults: {_controller: PlanITBundle:User:register }

PlanITBundle_listProject:
    pattern:  /planIT/project
    defaults: { _controller: PlanITBundle:Project:listProject }
    
PlanITBundle_addProject:
    pattern:  /planIT/project/add
    defaults: { _controller: PlanITBundle:Project:addProject, idproject: null }
    
PlanITBundle_editProject:
    pattern:  /planIT/project/edit/{idproject}
    defaults: { _controller: PlanITBundle:Project:addProject }
    
PlanITBundle_delProject:
    pattern:  /planIT/project/delete/{idproject}
    defaults: { _controller: PlanITBundle:Project:delProject }

PlanITBundle_detailProject:
    pattern:  /planIT/project/details/{idproject}
    defaults: {_controller: PlanITBundle:Project:detailsProject, idproject: null }
    requirements:
       idproject: \d+
    
PlanITBundle_listTask:
    pattern:  /planIT/task
    defaults: { _controller: PlanITBundle:Task:listTask }
    
PlanITBundle_addTask:
    pattern:  /planIT/task/add
    defaults: { _controller: PlanITBundle:Task:addTask, idassignment: null  }
    
PlanITBundle_editTask:
    pattern:  /planIT/task/edit/{idassignment}
    defaults: { _controller: PlanITBundle:Task:addTask }
    
PlanITBundle_delTask:
    pattern:  /planIT/project/delete/{idassignment}
    defaults: { _controller: PlanITBundle:Task:delTask }
    
PlanITBundle_listPerson:
    pattern:  /planIT/person
    defaults: {_controller: PlanITBundle:Person:listPerson }

PlanITBundle_addPerson:
    pattern:  /planIT/person/add
    defaults: {_controller: PlanITBundle:Person:addPerson, idperson: null }
    
PlanITBundle_editPerson:
    pattern:  /planIT/person/edit/{idperson}
    defaults: {_controller: PlanITBundle:Person:addPerson }
    
PlanITBundle_delPerson:
    pattern:  /planIT/project/delete/{idperson}
    defaults: { _controller: PlanITBundle:Person:delPerson }
    
PlanITBundle_addJob:
    pattern:  /planIT/job/add
    defaults: {_controller: PlanITBundle:Job:addJob, idjob: null }
    
PlanITBundle_editJob:
    pattern:  /planIT/job/edit/{idjob}
    defaults: {_controller: PlanITBundle:Job:addJob }
    
PlanITBundle_listCharge:
    pattern:  /planIT/charge
    defaults: { _controller: PlanITBundle:Charge:listCharge }
    
PlanITBundle_addCharge:
    pattern:  /planIT/charge/add
    defaults: { _controller: PlanITBundle:Charge:addCharge, idcharge: null  }
    
PlanITBundle_editCharge:
    pattern:  /planIT/charge/edit/{idassignment}
    defaults: { _controller: PlanITBundle:Charge:addCharge }
   
PlanITBundle_burndownFeedback:
    pattern:  /planIT/feedback/burndown
    defaults: {_controller: PlanITBundle:Feedback:burndownFeedback }
   
PlanITBundle_ganttFeedback:
    pattern:  /planIT/feedback/gantt/{idproject}
    defaults: {_controller: PlanITBundle:Feedback:ganttFeedback, idproject: null }
    requirements:
       idproject: \d+

PlanITBundle_pertFeedback:
    pattern:  /planIT/feedback/pert
    defaults: {_controller: PlanITBundle:Feedback:pertFeedback }
    
PlanITBundle_jsonevents:
    pattern:  /planIT/api/events
    defaults: { _controller: PlanITBundle:API:listCalEvents }
    
PlanITBundle_jsonresize:
    pattern:  /planIT/api/resize
    defaults: { _controller: PlanITBundle:API:editCalResizeEvents }
    
PlanITBundle_jsondrop:
    pattern:  /planIT/api/drop
    defaults: { _controller: PlanITBundle:API:editCalDropEvents }
    
PlanITBundle_jsongantt:
    pattern:  /planIT/api/gantt/{idproject}
    defaults: { _controller: PlanITBundle:API:listGanttEvents }
    