Flyers\PlanITBundle\Entity\Project:
  type: entity
  table: project
  repositoryClass: Flyers\PlanITBundle\Repository\ProjectRepository
  fields:
    idproject:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 45
      fixed: false
      nullable: false
    description:
      type: text
      nullable: true
    begin:
      type: date
      nullable: false
    end:
      type: date
      nullable: false
    realend:
      type: date
      nullable: true
  manyToOne:
    user:
      targetEntity: User
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        user:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
